### ISSUE TITLE
Create frontend 

### ISSUE THREAD

**Issue by sipian** [MerAuctions/MerAuctions#1]
Auction details page (MVP)
- [x] create html skeleton
    - [x] render item
    - [x] render list of bids (without data)
    - [x] render bid submit form
- [x] use socket.io for rendering live auction results (top 5 most recent bids)
- [x] tell user to register an id if not registered
    - [x] a page for registration
- [x] after registration, allow user to post price (bid)
- [x] after the auction is over, render the result

Main page (auction list)
- [x] render all auctions including name, image & description

**Comment by b-z** [comment]
Sign up button can be removed:
if a user has already signed up, then he can submit a bid;
otherwise, when he click the bid submit button, we give him sign up page, and then submit.
