### ISSUE TITLE
Backend Endpoints

### ISSUE THREAD

**Issue by sipian** [MerAuctions/MerAuctions#2]
- [x] GET / 
     - render list of auctions , with a button to click to go to auction.

- [x] GET /auctions/:id
    - render with auction name, description, image, end-time.
      (image sent as mongodb bytecode(hash))

- [x] GET /auctions/:id/bids
     - return array of top 5 bids [{"userid","timestamp","price"}]

- [x] POST /users
     - input JSON {"user_id": ""}
     - returns JSON {"success":true|false}

- [x] POST /auctions/:auction_id/users/:user_id/bids
     - input JSON{"price"}
     - returns JSON {"success":true|false}

- [x] GET /auctions/:id/result
    - result {"isAuctionCompleted"(bool), "userid", "price"}

@VamshiTeja http handler functions + server
@deepakbhatt329 DB functions + structures

**Comment by b-z** [comment]
Do we need `GET /auctions/:id/bids`?
I think it would be better if we render (fill in) the top 5 bids instantly in `GET /auctions/:id`.
We can let the `GET /auctions/:id/bids` to be an endpoint that returns all bids under the auction, and implement later (low priority).
