### ISSUE TITLE
deploy backend of CAP-THAT-PIC as separate heroku app

### ISSUE THREAD

**Issue by sahil505** [MerAuctions/MerAuctions#33]
In order to integrate merAuc with CAP-THAT-PIC. We need to generate descriptions for images uploaded by users on merAuc using CAP-THAT-PIC

**Comment by Rocuku** [comment]
Deployment: https://cat-that-pic-bak.herokuapp.com/api/v1/

Deploy succeed, but get an error when trying to get the caption:

> computervision.BaseClient#TagImage: Failure preparing request: StatusCode=0 -- Original Error: autorest: No scheme detected in URL /vision/v2.0

Is it about COMPUTER_VISION_KEY or URL? 
Can you help me with this?@shasjakka0390

**Comment by sahil505** [comment]
@Rocuku 
I think this is due to the credit card details missing in the Azure SDK.
